server:
    port: 80
    //context-path: /demo/

logging:
    level:
        org.loushang: TRACE 
    
spring:
    datasource:
        driverClassName : com.mysql.jdbc.Driver
        url: jdbc:mysql://101.132.128.194:3306/demo
        username: root
        password: root
        min-idle: 1
        max-active: 20
        test-on-borrow: true

mybatis:
    type-aliases-package: org.loushang.ldf.data
    mapper-locations: classpath:dao/*.xml
    configuration:mapUnderscoreToCamelCase: true
mapper:
    identity: MYSQL